### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by DuplexGaming** [gc2023/Necessities#1]
When will this plugin be released????????!?!!?!?!??!?!

**Comment by gc2023** [comment]
This plugin will be released when i finish it. I'm guessing probably around October - November...
Sorry if that's a little longer than expected!

**Comment by DuplexGaming** [comment]
Okay.

**Comment by DuplexGaming** [comment]
ok

**Comment by DuplexGaming** [comment]
just make sure u dont game to hard or else etan will gameryt
